name: Deploy Vue Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 显式指定在 ./dev 下安装依赖
      - name: Install dependencies
        run: npm install
        working-directory: ./dev

      # 显式指定在 ./dev 下进行编译
      - name: Build
        run: npm run build
        working-directory: ./dev

      # 从根目录视角上传打包好的静态文件夹
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dev/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4